project:
  type: website
  output-dir: _site

website:
  title: "Trotterize Hubbard"

format:
  html:
    theme: cerulean
    code-block-bg: true
    code-block-border-left: true
    code-fold: false
    markdown:
      hard_line_breaks: true
    toc: true
    toc-depth: 2
    number-sections: true
    mainfont: Inter

execute:
  enabled: true
