project:
  type: website
  output-dir: _site

website:
  title: "Trotterize Hubbard"

format:
  html:
    theme: cosmo
    code-fold: false
    highlight-style: github
    markdown:
      hard_line_breaks: true
