project:
  type: website
  output-dir: _site

website:
  title: "Trotterize Hubbard"

format:
  html:
    theme: cosmo
    mainfont: serif
    code-block-bg: true
    code-fold: false
    syntax-highlighting: kate
    markdown:
      hard_line_breaks: true
